image: node:alpine

cache:
  paths:
    - node_modules/
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run test
    - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - dist

pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - dev